### ISSUE TITLE
Fails to install babel

### ISSUE THREAD

**Issue by gilligan** [adnelson/nixfromnpm#58]
```
 $ nixfromnpm -p babel%5.8.23 -otest --no-cache
```
yields:

```
Failed to generate expressions for 2 downstream dependencies.
  esprima-fb@>=15001.1001.0-dev-harmony-fb <15001.1002.0
   Dependency of:
    babel@5.8.23 -> babel-core@5.8.35 -> regenerator@0.8.40
    babel@5.8.23 -> babel-core@5.8.35 -> regenerator@0.8.40 -> defs@1.1.1
    babel@5.8.23 -> babel-core@5.8.35 -> regenerator@0.8.40 -> commoner@0.10.4 -> recast@0.10.43
    babel@5.8.23 -> babel-core@5.8.35 -> regenerator@0.8.40 -> recast@0.10.33
Failed to build because: NoMatchingVersion >=15001.1001.0-dev-harmony-fb <15001.1002.0
  form-data@>=1.0.0-rc3 <1.1.0
   Dependency of:
    babel@5.8.23 -> chokidar@1.4.2 -> fsevents@1.0.7 -> node-pre-gyp@0.6.21 -> request@2.69.0
Failed to build because: NoMatchingVersion >=1.0.0-rc3 <1.1.0
Package babel@=5.8.23 built successfully.
```

Can you give me any pointers on how to solve this ?

**Comment by adnelson** [comment]
So the docs for this are not in this repo (which they should be) but [here[(https://github.com/adnelson/nix-node-packages#if-a-package-doesnt-build). Hopefully this helps. Most of the issues fetching packages have to do with my incomplete implementation of the semver spec. :(

**Comment by gilligan** [comment]
@adnelson thanks for your response. I followed those instructions but somehow it did not really work out:
 
https://github.com/gilligan/nixfromnpm-test

```
% nix-shell
error: anonymous function at /Users/tpflug/Development/nix/nodejs-testing/test/nodeLib/buildNodePackage.nix:1:1 called without required argument ‘nodejsSources’, at /Users/tpflug
/Development/nix/nodejs-testing/test/nodeLib/default.nix:80:22
```

The `master` branch has the versioning fixes whereas the `unfixed` branch is with the broken packages still. I did not make any changes beyond those but ran into the error above. Do you have any idea what is going on here ?

**Comment by adnelson** [comment]
Hey, sorry I was out yesterday. So I'd been doing some dev on the nix library part of this project, but I'm not sure it's all merged so it might be slightly inconsistent. I'll try to take a look today and get everything back into stability...

**Comment by gilligan** [comment]
@adnelson that would be so great. I was really glad to find your project because `npm2nix` is just not a viable solution. Now i really hope that I can actually pull this off with nixfromnpm ;) 

so i have my fingers crossed ;)

**Comment by adnelson** [comment]
No problem! Hopefully I'll be able to get this all nailed down very soon. In the meantime, if you're just trying to get a working nix expression for Babel, there's already one in the [`nix-node-packages`](https://github.com/adnelson/nix-node-packages) repo, so the quickest way would be just

```bash
git clone https://github.com/adnelson/nix-node-packages
nix-build nix-node-packages -A nodePackages.babel
```

**Comment by gilligan** [comment]
@adnelson thanks but it's not the right version plus i am working on "nixifying" a bigger project so that is only one part of it anyway.. ;)

**Comment by adnelson** [comment]
OK, so I pushed some changes that should fix this. I was able to use the `nixfromnpm` that got built to make an expression for `babel` (at version `6.5.2` but idk what you needed) which built successfully.

One of these changes was to use git submodules instead of relying on the user to check out the two repos we're depending on. This means that once you pull down the latest changes, you should run `git submodule update --init --recursive` before you do your `nix-build`. (It also means you can safely delete your clones of those two repos if you want). This is in the README now.

I'm happy to make these changes because of course the tool should work, but I'd still encourage you to use the `nix-node-packages` repo. Using that repo means that packages you might need in the future (and/or their dependencies) will be likely to already be defined, and also that bug fixes will be available. If you need a version of a package which isn't in the repo you can still use `nixfromnpm` to add it. Really the only reason IMO to avoid it is code size, which isn't usually an issue because nix code isn't typically deployed anywhere. If you have private packages you're trying to define with nix, you have a few options: you can fork `nix-node-packages`, or use the `--extend` option to put the private packages in their own folder.

Of course, there's nothing *wrong* with just starting from scratch :smile: 

Please reopen this if things don't work.
