### ISSUE TITLE
dev-depth for package.json parsing

### ISSUE THREAD

**Issue by gilligan** [adnelson/nixfromnpm#73]
From reading the documentation the behaviour of `--dev-depth 1` is unclear to me when used in combination with parsing a `package.json` file. I would say the desired behaviour should be that it installs all `dependencies` and `devDependencies` listed in the `package.json` - is that actually the case?

**Comment by ixmatus** [comment]
@gilligan it shouldn't "install" them because they are usually build-time dependencies but if you want the dev dependencies installed you can override the package and set:

```
skipDevDependencyCleanup = true;
```

I'm going to close this ticket as I think that takes care of this concern. If I've misinterpreted the issue though, please reopen this.
