### ISSUE TITLE
Don't use release candidate or beta versions unless explicitly requested

### ISSUE THREAD

**Issue by ns-gbernsleone** [adnelson/nixfromnpm#87]
`-rc` and `-beta` versions are prioritized over stable versions, which doesn't seem like the behavior most users expect. It would probably be better to alter the priority so that only happens if a flag is set.

**Comment by ixmatus** [comment]
Furthermore, it breaks most packages because if `^` or `~` are used in a dep constraint and a package is given whose semantic version would match the constraint but has an attribute part (e.g. a `-rc` or `-0` or `-candidate`) npm will reject it.

I believe this issue is more appropriate for the `semver` package, though. Since it should know to reject npm packages with hyphenated parts in the version if and only if there is a `^` or `~` in the version and no hyphenated part in the version constraint.

**Comment by ixmatus** [comment]
More specifically:

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.
